trying to set permissions

diff --git a/.github/workflows/nightly-release.yml b/.github/workflows/nightly-release.yml
--- a/.github/workflows/nightly-release.yml
+++ b/.github/workflows/nightly-release.yml
@@ -4,10 +4,14 @@ on:
     branches: [ dev ]
 
 
+
+
+env:
+  GITHUB_REPOSITORY: domonik/RAPDOR
+  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+
 permissions:
   contents: write
-
-
 
 jobs:
   delete-tag:
@@ -20,6 +24,10 @@ jobs:
       - name: del-tag
         run: |
           RELEASE_ID=$(curl -s -H "Authorization: token ${GITHUB_TOKEN}" "https://api.github.com/repos/${GITHUB_REPOSITORY}/releases/tags/nightly" | jq -r '.id')
+          if [ "${RELEASE_ID}" = "null" ]; then
+            echo "Error: Release not found for tag '${TAG_NAME}'."
+            exit 1
+          fi
           curl -X DELETE -H "Authorization: token ${GITHUB_TOKEN}" "https://api.github.com/repos/${GITHUB_REPOSITORY}/releases/${RELEASE_ID}"
           git push --delete origin nightly
           git tag --delete nightly
